/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.paas.controller;

import com.paas.model.BankSearchRequest;
import com.paas.model.BankSearchResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-10-10T19:31:03.922+05:30")

@Api(value = "bankSearch", description = "the bankSearch API")
public interface BankSearchApi {

    @ApiOperation(value = "", nickname = "doBankSearch", notes = "Retrieves Bank Details based on the search criteria", response = BankSearchResponse.class, tags={ "BankSearch", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response, with a bank search request.", response = BankSearchResponse.class),
        @ApiResponse(code = 404, message = "The requested bank was not found.") })
    @RequestMapping(value = "/bankSearch",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<BankSearchResponse> doBankSearch(@ApiParam(value = "Bank Search request input parameters" ,required=true )  @Valid @RequestBody BankSearchRequest bankSearchRequest) throws Exception;

}
