/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.paas.controller;

import com.paas.model.BankBranchSearchRequest;
import com.paas.model.BankBranchSearchResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-10-05T14:50:25.040+05:30")

@Api(value = "bankBranchSearch", description = "the bankBranchSearch API")
public interface BankBranchSearchApi {

    @ApiOperation(value = "", nickname = "doBankBranchSearch", notes = "Retrieves Bank Details based on the search criteria", response = BankBranchSearchResponse.class, tags={ "BankBranchSearch", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response, with a bank branch search request.", response = BankBranchSearchResponse.class),
        @ApiResponse(code = 404, message = "The requested bank branch was not found.") })
    @RequestMapping(value = "/bankBranchSearch",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<BankBranchSearchResponse> doBankBranchSearch(@ApiParam(value = "Bank Branch Search request input parameters" ,required=true )  @Valid @RequestBody BankBranchSearchRequest bankBranchSearchRequest) throws Exception;

}
