/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.paas.controller;

import com.paas.model.CreateTransactionRequest;
import com.paas.model.CreateTransactionResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-10-11T10:59:35.791+05:30")

@Api(value = "createTransaction", description = "the createTransaction API")
public interface CreateTransactionApi {

    @ApiOperation(value = "", nickname = "doCreateTxn", notes = "To create the transaction", response = CreateTransactionResponse.class, tags={ "CreateRequest", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Create response, with proper description.", response = CreateTransactionResponse.class),
        @ApiResponse(code = 404, message = "The requested resource was not found.") })
    @RequestMapping(value = "/createTransaction",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<CreateTransactionResponse> doCreateTxn(@ApiParam(value = "Create request input parameters" ,required=true )  @Valid @RequestBody CreateTransactionRequest createTransactionRequest);

}
