/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.paas.controller;

import com.paas.model.ReleaseTransactionRequest;
import com.paas.model.ReleaseTransactionResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-10-11T14:17:32.589+05:30")

@Api(value = "releaseTransaction", description = "the releaseTransaction API")
public interface ReleaseTransactionApi {

    @ApiOperation(value = "Releases transactions", nickname = "doReleaseTxn", notes = "Release the requested transactions", response = ReleaseTransactionResponse.class, tags={ "ReleasesTransaction", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response, with a representation of the ReleaseTxn", response = ReleaseTransactionResponse.class) })
    @RequestMapping(value = "/releaseTransaction",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ReleaseTransactionResponse> doReleaseTxn(@ApiParam(value = "Details of release requested transactions" ,required=true )  @Valid @RequestBody ReleaseTransactionRequest releaseTransactionRequest);

}
