/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.paas.controller;

import com.paas.model.TransactionEnquiryRequest;
import com.paas.model.TransactionEnquiryResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-10-10T18:11:07.886+05:30")

@Api(value = "txnEnquiry", description = "the txnEnquiry API")
public interface TxnEnquiryApi {

    @ApiOperation(value = "", nickname = "doTxnEnquiry", notes = "Retrieves Txn Details based on the search criteria", response = TransactionEnquiryResponse.class, tags={ "TxnEnquiry", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response, with a Enquiry search request.", response = TransactionEnquiryResponse.class),
        @ApiResponse(code = 404, message = "The requested bank was not found.") })
    @RequestMapping(value = "/txnEnquiry",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<TransactionEnquiryResponse> doTxnEnquiry(@ApiParam(value = "Enquiry Search request input parameters" ,required=true )  @Valid @RequestBody TransactionEnquiryRequest transactionEnquiryRequest);

}
